### ISSUE TITLE
Label Info Icon: Helpful information goes here.

### ISSUE THREAD

**Issue by enrique-lumen** [CenturyLink/Chi#1312]
Label Info Icon default message is getting displayed as **Helpful information goes here**.

https://github.com/CenturyLink/Chi/blob/049be37f0bad375d71a47881b4c2750d37d88d51/src/custom-elements/src/components/label/label.tsx#L37

`@Prop({ reflect: true }) infoIconMessage = 'Helpful information goes here.';`

Insted, should be blank string as default message:

`@Prop({ reflect: true }) infoIconMessage = '';`

**Comment by josecarlosgonzalezv** [comment]
This has been fixed here: https://github.com/CenturyLink/chi-custom-elements/pull/14 and it is now released.

https://lib.lumen.com/chi/latest/getting-started/whats-new/?theme=Portal#chi-v6-9-0
